namespace AcDream.UI.Abstractions.Input;

public enum InputAction
{
    /// <summary>Sentinel — no action. Reserved for "unbound".</summary>
    None = 0,

    MovementForward,
    /// <summary>Move backward.</summary>
    MovementBackup,
    MovementTurnLeft,
    MovementTurnRight,
    /// <summary>Strafe (sidestep) to the left.</summary>
    MovementStrafeLeft,
    /// <summary>Strafe (sidestep) to the right.</summary>
    MovementStrafeRight,
    MovementWalkMode,
    MovementRunLock,
    MovementJump,
    MovementStop,
    Ready,
    Sitting,
    Crouch,
    Sleeping,

    // ── ItemSelectionCommands ─────────────────────────────
    /// <summary>Pick up the selected item.</summary>
    SelectionPickUp,
    /// <summary>Split a stack of the selected item.</summary>
    SelectionSplitStack,
    SelectionPreviousSelection,
    SelectionClosestCompassItem,
    SelectionPreviousCompassItem,
    SelectionNextCompassItem,
    SelectionClosestItem,
    /// <summary>Previous item in radius.</summary>
    SelectionPreviousItem,
    /// <summary>Next item in radius.</summary>
    SelectionNextItem,
    SelectionClosestMonster,
    /// <summary>Previous monster.</summary>
    SelectionPreviousMonster,
    /// <summary>Next monster.</summary>
    SelectionNextMonster,
    /// <summary>Most-recent attacker (for retaliation).</summary>
    SelectionLastAttacker,
    SelectionClosestPlayer,
    /// <summary>Previous player.</summary>
    SelectionPreviousPlayer,
    /// <summary>Next player.</summary>
    SelectionNextPlayer,
    /// <summary>Previous fellow.</summary>
    SelectionPreviousFellow,
    /// <summary>Next fellow.</summary>
    SelectionNextFellow,
    SelectionExamine,

    UseSelected,
    EscapeKey,
    LOGOUT,
    ToggleHelp,
    TogglePluginManager,
    ToggleAllegiancePanel,
    ToggleFellowshipPanel,
    ToggleSpellbookPanel,
    ToggleSpellComponentsPanel,
    ToggleAttributesPanel,
    ToggleSkillsPanel,
    ToggleWorldPanel,
    ToggleOptionsPanel,
    ToggleInventoryPanel,
    ToggleFloatingChatWindow1,
    ToggleFloatingChatWindow2,
    ToggleFloatingChatWindow3,
    ToggleFloatingChatWindow4,
    CaptureScreenshot,

    // ── QuickslotCommands ─────────────────────────────────
    UseQuickSlot_1,
    UseQuickSlot_2,
    UseQuickSlot_3,
    UseQuickSlot_4,
    UseQuickSlot_5,
    UseQuickSlot_6,
    UseQuickSlot_7,
    UseQuickSlot_8,
    UseQuickSlot_9,
    SelectQuickSlot_1,
    SelectQuickSlot_2,
    SelectQuickSlot_3,
    SelectQuickSlot_4,
    SelectQuickSlot_5,
    SelectQuickSlot_6,
    SelectQuickSlot_7,
    SelectQuickSlot_8,
    SelectQuickSlot_9,
    UseQuickSlot_14,
    UseQuickSlot_15,
    UseQuickSlot_16,
    UseQuickSlot_17,
    UseQuickSlot_18,
    CreateShortcut,

    ToggleChatEntry,
    EnterChatMode,

    CombatToggleCombat,
    CombatDecreaseAttackPower,
    CombatIncreaseAttackPower,
    CombatLowAttack,
    CombatMediumAttack,
    CombatHighAttack,
    CombatDecreaseMissileAccuracy,
    CombatIncreaseMissileAccuracy,
    CombatAimLow,
    CombatAimMedium,
    CombatAimHigh,
    CombatPrevSpellTab,
    CombatNextSpellTab,
    CombatPrevSpell,
    CombatCastCurrentSpell,
    CombatNextSpell,
    CombatFirstSpellTab,
    CombatLastSpellTab,
    CombatFirstSpell,
    CombatLastSpell,
    UseSpellSlot_1,
    UseSpellSlot_2,
    UseSpellSlot_3,
    UseSpellSlot_4,
    UseSpellSlot_5,
    UseSpellSlot_6,
    UseSpellSlot_7,
    UseSpellSlot_8,
    UseSpellSlot_9,

    Cry,
    Laugh,
    Cheer,
    Wave,
    PointState,

    CameraActivateAlternateMode,
    /// <summary>Hold-MMB instant mouse-look — hardcoded behavior in K.2.</summary>
    CameraInstantMouseLook,
    CameraRotateLeft,
    CameraRotateRight,
    CameraRotateUp,
    CameraRotateDown,
    CameraMoveToward,
    CameraMoveAway,
    CameraViewDefault,
    CameraViewFirstPerson,
    CameraViewLookDown,
    CameraViewMapMode,

    ScrollUp,
    ScrollDown,

    SelectLeft,
    SelectRight,
    SelectMid,
    SelectDblLeft,
    SelectDblRight,
    SelectDblMid,

    // ── Acdream debug actions (existing F-key behavior) ──
    /// <summary>F1 toggles entire DebugPanel visibility (acdream-only).</summary>
    AcdreamToggleDebugPanel,
    AcdreamToggleCollisionWires,
    AcdreamDumpNearby,
    AcdreamCycleTimeOfDay,
    /// <summary>F8 decreases mouse sensitivity.</summary>
    AcdreamSensitivityDown,
    /// <summary>F9 increases mouse sensitivity.</summary>
    AcdreamSensitivityUp,
    AcdreamCycleWeather,
    AcdreamToggleAudioMute,
    AcdreamToggleFlyMode,
    AcdreamTogglePlayerMode,
    AcdreamRmbOrbitHold,
    AcdreamFlyDown,

    CameraZoomIn,
    CameraZoomOut,
    CameraRaise,
    CameraLower,


    CameraAlternateMoveToward,
    CameraAlternateMoveAway,
    CameraAlternateRotateLeft,
    CameraAlternateRotateRight,
    CameraAlternateRotateUp,
    CameraAlternateRotateDown,
    CameraAlternateViewDefault,
    CameraAlternateViewFirstPerson,
    CameraAlternateViewLookDown,
    CameraAlternateViewMapMode,

    UseSpellSlot_10,
    UseSpellSlot_11,
    UseSpellSlot_12,

    EmoteAfkState,
    EmoteAkimbo,
    EmoteAToyotState,
    EmoteAkimboState,
    EmoteAtEaseState,
    EmoteBeckon,
    EmoteBeSeeingYou,
    EmoteBlowKiss,
    EmoteBowDeep,
    EmoteBowDeepState,
    EmoteClapHands,
    EmoteClapHandsState,
    EmoteCringe,
    EmoteCrossArmsState,
    EmoteCurtseyState,
    EmoteDrudgeDance,
    EmoteDrudgeDanceState,
    EmoteHaveASeat,
    EmoteHaveASeatState,
    EmoteHeartyLaugh,
    EmoteHelper,
    EmoteKneel,
    EmoteKneelState,
    EmoteKnock,
    EmoteLeanState,
    EmoteMeditateState,
    EmoteMimeDrinking,
    EmoteMimeEating,
    EmoteMock,
    EmoteNod,
    EmoteNudgeLeft,
    EmoteNudgeRight,
    EmotePlead,
    EmotePleadState,
    EmotePoint,
    EmotePointDown,
    EmotePointDownState,
    EmotePointLeft,
    EmotePointLeftState,
    EmotePointRight,
    EmotePointRightState,
    EmotePossumState,
    EmotePray,
    EmotePrayState,
    EmoteReadState,
    EmoteSalute,
    EmoteSaluteState,
    EmoteScanHorizon,
    EmoteScratchHead,
    EmoteScratchHeadState,
    EmoteShakeFist,
    EmoteShakeFistState,
    EmoteShakeHead,
    EmoteShiver,
    EmoteShiverState,
    EmoteShoo,
    EmoteShrug,
    EmoteSitState,
    EmoteSitBackState,
    EmoteSitCrossleggedState,
    EmoteSlouch,
    EmoteSlouchState,
    EmoteSmackHead,
    EmoteSnowAngelState,
    EmoteSpit,
    EmoteSurrender,
    EmoteSurrenderState,
    EmoteTalkToTheHandState,
    EmoteTapFoot,
    EmoteTapFootState,
    EmoteTeapot,
    EmoteThinkerState,
    EmoteWarmHands,
    EmoteWaveState,
    EmoteWaveLow,
    EmoteWaveHigh,
    EmoteWinded,
    EmoteWindedState,
    EmoteWoah,
    EmoteWoahState,
    EmoteYawnAndStretch,
    EmoteYmca,

    SelectionSelf,
    SelectionPlaceInInventory,
    SelectionUseClosestUnopenedCorpse,
    SelectionUseNextUnopenedCorpse,
    SelectionGiveToTarget,
    SelectionDrop,
    SelectionPlaceInMainPack,
    SelectionClosestUnopenedCorpse,
    SelectionNextUnopenedCorpse,

    ToggleAbuseReportingPanel,
    ToggleCharacterInfoPanel,
    TogglePositiveMagicPanel,
    ToggleNegativeMagicPanel,
    ToggleLinkStatusPanel,
    ToggleUrgentAssistancePanel,
    ToggleVitaePanel,
    ToggleSocialPanel,
    ToggleSpellManagementPanel,
    ToggleCharacterDetailPanel,
    ToggleMapPage,
    ToggleHousePage,
    ToggleGameplayOptionsPage,
    ToggleCharacterSettingsPage,
    ToggleConfigurationPage,
    ToggleCompass,
    ToggleKeyboardConfiguration,
    ToggleFriendsPage,
    ToggleCharacterTitlesPage,
    ToggleQuestDetailPanel,
    ToggleQuestJournalPage,
    ToggleJournalPageList,
    ToggleContractsPage,

    ChatMonarchReply,
    ChatPatronReply,
    ChatReply,
    ChatStartCommand,
    ChatTellToSelected,

    UseQuickSlot_10,
    UseQuickSlot_11,
    UseQuickSlot_12,
    UseQuickSlot_13,

    ToggleCharacterOptionAutoRepeatAttack,
    ToggleCharacterOptionIgnoreAllegianceRequests,
    ToggleCharacterOptionIgnoreFellowshipRequests,
    ToggleCharacterOptionIgnoreTradeRequests,
    ToggleCharacterOptionPersistentAtDay,
    ToggleCharacterOptionAllowGive,
    ToggleCharacterOptionViewCombatTarget,
    ToggleCharacterOptionShowTooltips,
    ToggleCharacterOptionUseDeception,
    ToggleCharacterOptionToggleRun,
    ToggleCharacterOptionStayInChatMode,
    ToggleCharacterOptionAdvancedCombatUi,
    ToggleCharacterOptionAutoTarget,
    ToggleCharacterOptionVividTargetingIndicator,
    ToggleCharacterOptionFellowshipShareXp,
    ToggleCharacterOptionAcceptLootPermits,
    ToggleCharacterOptionFellowshipShareLoot,
    ToggleCharacterOptionFellowshipAutoAcceptRequests,
    ToggleCharacterOptionCoordinatesOnRadar,
    ToggleCharacterOptionSpellDuration,
    ToggleCharacterOptionDisableHouseRestrictionEffects,
    ToggleCharacterOptionDragItemOnPlayerOpensSecureTrade,
    ToggleCharacterOptionDisplayAllegianceLogonNotifications,
    ToggleCharacterOptionUseChargeAttack,
    ToggleCharacterOptionUseCraftSuccessDialog,
    ToggleCharacterOptionListenToAllegianceChat,
    ToggleCharacterOptionDisplayDateOfBirth,
    ToggleCharacterOptionDisplayAge,
    ToggleCharacterOptionDisplayChessRank,
    ToggleCharacterOptionDisplayFishingSkill,
    ToggleCharacterOptionDisplayNumberDeaths,
    ToggleCharacterOptionDisplayTimeStamps,
    ToggleCharacterOptionSalvageMultiple,
    ToggleCharacterOptionListenToGeneralChat,
    ToggleCharacterOptionListenToTradeChat,
    ToggleCharacterOptionListenToLfgChat,
    ToggleCharacterOptionListenToRoleplayChat,
    ToggleCharacterOptionDisplayNumberCharacterTitles,
    ToggleCharacterOptionMainPackPreferred,
    ToggleCharacterOptionLeadMissileTargets,
    ToggleCharacterOptionUseFastMissiles,
    ToggleCharacterOptionFilterLanguage,
    ToggleCharacterOptionConfirmVolatileRareUse,
    ToggleCharacterOptionListenToSocietyChat,
    ToggleCharacterOptionShowHelm,
    ToggleCharacterOptionDisableDistanceFog,
    ToggleCharacterOptionShowCloak,
    ToggleCharacterOptionSideBySideVitals,
}
